#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
services:
  web:
    deploy:
      placement:
        constraints:
        - node.role == worker
    image: secobau/spring-petclinic:0.4
    ports:
      - 8080:8080
version: '3.8'
#########################################################################
